// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v2 "github.com/tetrateio/tetrate/api/tsb/application/v2"
)

const applicationAPICollection = "apis"

var (
	_ resource.Resource                = (*applicationAPIResource)(nil)
	_ resource.ResourceWithConfigure   = (*applicationAPIResource)(nil)
	_ resource.ResourceWithImportState = (*applicationAPIResource)(nil)
)

// NewApplicationAPIResource constructs the tsb_application_api resource.
func NewApplicationAPIResource() resource.Resource {
	return &applicationAPIResource{}
}

type applicationAPIResource struct {
	client *client
}

func (r *applicationAPIResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application_api"
}
func (r *applicationAPIResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.APISchema())
}
func (r *applicationAPIResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *applicationAPIResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ApplicationAPIModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandApplicationAPI(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewApplicationsClient(r.client.conn)
	created, err := c.CreateAPI(ctx, &v2.CreateAPIRequest{
		Api:    msg,
		Name:   plan.Name.ValueString(),
		Parent: plan.Parent.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create ApplicationAPI", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenApplicationAPI(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *applicationAPIResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ApplicationAPIModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewApplicationsClient(r.client.conn)
	got, err := c.GetAPI(ctx, &v2.GetAPIRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read ApplicationAPI", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenApplicationAPI(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *applicationAPIResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ApplicationAPIModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandApplicationAPI(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewApplicationsClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetAPI(ctx, &v2.GetAPIRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read ApplicationAPI before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateAPI(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update ApplicationAPI", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenApplicationAPI(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *applicationAPIResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ApplicationAPIModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewApplicationsClient(r.client.conn)
	_, err := c.DeleteAPI(ctx, &v2.DeleteAPIRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete ApplicationAPI", err.Error())
		return
	}
}
func (r *applicationAPIResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, applicationAPICollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
