// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const clusterOnboardingConfigCollection = "onboarding"

var (
	_ resource.Resource                = (*clusterOnboardingConfigResource)(nil)
	_ resource.ResourceWithConfigure   = (*clusterOnboardingConfigResource)(nil)
	_ resource.ResourceWithImportState = (*clusterOnboardingConfigResource)(nil)
)

// NewClusterOnboardingConfigResource constructs the tsb_cluster_onboarding_config resource.
func NewClusterOnboardingConfigResource() resource.Resource {
	return &clusterOnboardingConfigResource{}
}

type clusterOnboardingConfigResource struct {
	client *client
}

func (r *clusterOnboardingConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cluster_onboarding_config"
}
func (r *clusterOnboardingConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.ClusterOnboardingConfigSchema())
}
func (r *clusterOnboardingConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *clusterOnboardingConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ClusterOnboardingConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandClusterOnboardingConfig(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewClustersClient(r.client.conn)
	created, err := c.CreateClusterOnboardingConfig(ctx, &v2.CreateClusterOnboardingConfigRequest{
		Config: msg,
		Name:   plan.Name.ValueString(),
		Parent: plan.Parent.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create ClusterOnboardingConfig", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenClusterOnboardingConfig(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *clusterOnboardingConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ClusterOnboardingConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewClustersClient(r.client.conn)
	got, err := c.GetClusterOnboardingConfig(ctx, &v2.GetClusterOnboardingConfigRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read ClusterOnboardingConfig", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenClusterOnboardingConfig(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *clusterOnboardingConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ClusterOnboardingConfigModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandClusterOnboardingConfig(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewClustersClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetClusterOnboardingConfig(ctx, &v2.GetClusterOnboardingConfigRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read ClusterOnboardingConfig before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateClusterOnboardingConfig(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update ClusterOnboardingConfig", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenClusterOnboardingConfig(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *clusterOnboardingConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ClusterOnboardingConfigModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewClustersClient(r.client.conn)
	_, err := c.DeleteClusterOnboardingConfig(ctx, &v2.DeleteClusterOnboardingConfigRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete ClusterOnboardingConfig", err.Error())
		return
	}
}
func (r *clusterOnboardingConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, clusterOnboardingConfigCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
