// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/extension/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const extensionWasmExtensionCollection = "extensions"

var (
	_ resource.Resource                = (*extensionWasmExtensionResource)(nil)
	_ resource.ResourceWithConfigure   = (*extensionWasmExtensionResource)(nil)
	_ resource.ResourceWithImportState = (*extensionWasmExtensionResource)(nil)
)

// NewExtensionWasmExtensionResource constructs the tsb_extension_wasm_extension resource.
func NewExtensionWasmExtensionResource() resource.Resource {
	return &extensionWasmExtensionResource{}
}

type extensionWasmExtensionResource struct {
	client *client
}

func (r *extensionWasmExtensionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_extension_wasm_extension"
}
func (r *extensionWasmExtensionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.WasmExtensionSchema())
}
func (r *extensionWasmExtensionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *extensionWasmExtensionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ExtensionWasmExtensionModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandExtensionWasmExtension(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWasmExtensionsClient(r.client.conn)
	created, err := c.CreateWasmExtension(ctx, &v2.CreateWasmExtensionRequest{
		Name:          plan.Name.ValueString(),
		Parent:        plan.Parent.ValueString(),
		WasmExtension: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create ExtensionWasmExtension", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenExtensionWasmExtension(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *extensionWasmExtensionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ExtensionWasmExtensionModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWasmExtensionsClient(r.client.conn)
	got, err := c.GetWasmExtension(ctx, &v2.GetWasmExtensionRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read ExtensionWasmExtension", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenExtensionWasmExtension(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *extensionWasmExtensionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ExtensionWasmExtensionModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandExtensionWasmExtension(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWasmExtensionsClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetWasmExtension(ctx, &v2.GetWasmExtensionRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read ExtensionWasmExtension before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateWasmExtension(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update ExtensionWasmExtension", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenExtensionWasmExtension(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *extensionWasmExtensionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ExtensionWasmExtensionModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWasmExtensionsClient(r.client.conn)
	_, err := c.DeleteWasmExtension(ctx, &v2.DeleteWasmExtensionRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete ExtensionWasmExtension", err.Error())
		return
	}
}
func (r *extensionWasmExtensionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, extensionWasmExtensionCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
