// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v1alpha1 "github.com/tetrateio/tetrate/api/install/dataplane/v1alpha1"
	v2 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
)

const gatewayInstallGatewayCollection = "installgateways"

var (
	_ resource.Resource                = (*gatewayInstallGatewayResource)(nil)
	_ resource.ResourceWithConfigure   = (*gatewayInstallGatewayResource)(nil)
	_ resource.ResourceWithImportState = (*gatewayInstallGatewayResource)(nil)
)

// NewGatewayInstallGatewayResource constructs the tsb_gateway_install_gateway resource.
func NewGatewayInstallGatewayResource() resource.Resource {
	return &gatewayInstallGatewayResource{}
}

type gatewayInstallGatewayResource struct {
	client *client
}

func (r *gatewayInstallGatewayResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_install_gateway"
}
func (r *gatewayInstallGatewayResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v1alpha1.GatewaySpecSchema())
}
func (r *gatewayInstallGatewayResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *gatewayInstallGatewayResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayInstallGatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayInstallGateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	created, err := c.CreateInstallGateway(ctx, &v2.CreateInstallGatewayRequest{
		Gateway: msg,
		Name:    plan.Name.ValueString(),
		Parent:  plan.Parent.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create GatewayInstallGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGateway(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayInstallGatewayResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayInstallGatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	got, err := c.GetInstallGateway(ctx, &v2.GetInstallGatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read GatewayInstallGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGateway(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gatewayInstallGatewayResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayInstallGatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayInstallGateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetInstallGateway(ctx, &v2.GetInstallGatewayRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read GatewayInstallGateway before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateInstallGateway(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update GatewayInstallGateway", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGateway(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayInstallGatewayResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayInstallGatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	_, err := c.DeleteInstallGateway(ctx, &v2.DeleteInstallGatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete GatewayInstallGateway", err.Error())
		return
	}
}
func (r *gatewayInstallGatewayResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, gatewayInstallGatewayCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
