// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v2 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
)

const gatewaySharedGatewayReferenceGrantCollection = "sharedgatewayreferencegrants"

var (
	_ resource.Resource                = (*gatewaySharedGatewayReferenceGrantResource)(nil)
	_ resource.ResourceWithConfigure   = (*gatewaySharedGatewayReferenceGrantResource)(nil)
	_ resource.ResourceWithImportState = (*gatewaySharedGatewayReferenceGrantResource)(nil)
)

// NewGatewaySharedGatewayReferenceGrantResource constructs the tsb_gateway_shared_gateway_reference_grant resource.
func NewGatewaySharedGatewayReferenceGrantResource() resource.Resource {
	return &gatewaySharedGatewayReferenceGrantResource{}
}

type gatewaySharedGatewayReferenceGrantResource struct {
	client *client
}

func (r *gatewaySharedGatewayReferenceGrantResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_shared_gateway_reference_grant"
}
func (r *gatewaySharedGatewayReferenceGrantResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.SharedGatewayReferenceGrantSchema())
}
func (r *gatewaySharedGatewayReferenceGrantResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *gatewaySharedGatewayReferenceGrantResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewaySharedGatewayReferenceGrantModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewaySharedGatewayReferenceGrant(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	created, err := c.CreateSharedGatewayReferenceGrant(ctx, &v2.CreateSharedGatewayReferenceGrantRequest{
		Name:                        plan.Name.ValueString(),
		Parent:                      plan.Parent.ValueString(),
		SharedGatewayReferenceGrant: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create GatewaySharedGatewayReferenceGrant", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewaySharedGatewayReferenceGrant(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewaySharedGatewayReferenceGrantResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewaySharedGatewayReferenceGrantModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	got, err := c.GetSharedGatewayReferenceGrant(ctx, &v2.GetSharedGatewayReferenceGrantRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read GatewaySharedGatewayReferenceGrant", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewaySharedGatewayReferenceGrant(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gatewaySharedGatewayReferenceGrantResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewaySharedGatewayReferenceGrantModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewaySharedGatewayReferenceGrant(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetSharedGatewayReferenceGrant(ctx, &v2.GetSharedGatewayReferenceGrantRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read GatewaySharedGatewayReferenceGrant before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateSharedGatewayReferenceGrant(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update GatewaySharedGatewayReferenceGrant", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewaySharedGatewayReferenceGrant(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewaySharedGatewayReferenceGrantResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewaySharedGatewayReferenceGrantModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	_, err := c.DeleteSharedGatewayReferenceGrant(ctx, &v2.DeleteSharedGatewayReferenceGrantRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete GatewaySharedGatewayReferenceGrant", err.Error())
		return
	}
}
func (r *gatewaySharedGatewayReferenceGrantResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, gatewaySharedGatewayReferenceGrantCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
