// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v2 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
)

const gatewayIngressGatewayCollection = "ingressgateways"

var (
	_ resource.Resource                = (*gatewayIngressGatewayResource)(nil)
	_ resource.ResourceWithConfigure   = (*gatewayIngressGatewayResource)(nil)
	_ resource.ResourceWithImportState = (*gatewayIngressGatewayResource)(nil)
)

// NewGatewayIngressGatewayResource constructs the tsb_gateway_ingress_gateway resource.
func NewGatewayIngressGatewayResource() resource.Resource {
	return &gatewayIngressGatewayResource{}
}

type gatewayIngressGatewayResource struct {
	client *client
}

func (r *gatewayIngressGatewayResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_ingress_gateway"
}
func (r *gatewayIngressGatewayResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.IngressGatewaySchema())
}
func (r *gatewayIngressGatewayResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *gatewayIngressGatewayResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayIngressGatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayIngressGateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	created, err := c.CreateIngressGateway(ctx, &v2.CreateIngressGatewayRequest{
		IngressGateway: msg,
		Name:           plan.Name.ValueString(),
		Parent:         plan.Parent.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create GatewayIngressGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayIngressGateway(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayIngressGatewayResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayIngressGatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	got, err := c.GetIngressGateway(ctx, &v2.GetIngressGatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read GatewayIngressGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayIngressGateway(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gatewayIngressGatewayResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayIngressGatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayIngressGateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetIngressGateway(ctx, &v2.GetIngressGatewayRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read GatewayIngressGateway before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateIngressGateway(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update GatewayIngressGateway", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayIngressGateway(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayIngressGatewayResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayIngressGatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	_, err := c.DeleteIngressGateway(ctx, &v2.DeleteIngressGatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete GatewayIngressGateway", err.Error())
		return
	}
}
func (r *gatewayIngressGatewayResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, gatewayIngressGatewayCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
