// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const gatewayInstallGatewayTemplateCollection = "installgatewaytemplates"

var (
	_ resource.Resource                = (*gatewayInstallGatewayTemplateResource)(nil)
	_ resource.ResourceWithConfigure   = (*gatewayInstallGatewayTemplateResource)(nil)
	_ resource.ResourceWithImportState = (*gatewayInstallGatewayTemplateResource)(nil)
)

// NewGatewayInstallGatewayTemplateResource constructs the tsb_gateway_install_gateway_template resource.
func NewGatewayInstallGatewayTemplateResource() resource.Resource {
	return &gatewayInstallGatewayTemplateResource{}
}

type gatewayInstallGatewayTemplateResource struct {
	client *client
}

func (r *gatewayInstallGatewayTemplateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_install_gateway_template"
}
func (r *gatewayInstallGatewayTemplateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.InstallGatewayTemplateSchema())
}
func (r *gatewayInstallGatewayTemplateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *gatewayInstallGatewayTemplateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayInstallGatewayTemplateModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayInstallGatewayTemplate(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	created, err := c.CreateInstallGatewayTemplate(ctx, &v2.CreateInstallGatewayTemplateRequest{
		Name:     plan.Name.ValueString(),
		Parent:   plan.Parent.ValueString(),
		Template: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create GatewayInstallGatewayTemplate", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGatewayTemplate(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayInstallGatewayTemplateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayInstallGatewayTemplateModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	got, err := c.GetInstallGatewayTemplate(ctx, &v2.GetInstallGatewayTemplateRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read GatewayInstallGatewayTemplate", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGatewayTemplate(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gatewayInstallGatewayTemplateResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayInstallGatewayTemplateModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayInstallGatewayTemplate(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetInstallGatewayTemplate(ctx, &v2.GetInstallGatewayTemplateRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read GatewayInstallGatewayTemplate before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateInstallGatewayTemplate(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update GatewayInstallGatewayTemplate", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayInstallGatewayTemplate(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayInstallGatewayTemplateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayInstallGatewayTemplateModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	_, err := c.DeleteInstallGatewayTemplate(ctx, &v2.DeleteInstallGatewayTemplateRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete GatewayInstallGatewayTemplate", err.Error())
		return
	}
}
func (r *gatewayInstallGatewayTemplateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, gatewayInstallGatewayTemplateCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
