// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const gatewayTier1GatewayCollection = "tier1gateways"

var (
	_ resource.Resource                = (*gatewayTier1GatewayResource)(nil)
	_ resource.ResourceWithConfigure   = (*gatewayTier1GatewayResource)(nil)
	_ resource.ResourceWithImportState = (*gatewayTier1GatewayResource)(nil)
)

// NewGatewayTier1GatewayResource constructs the tsb_gateway_tier1_gateway resource.
func NewGatewayTier1GatewayResource() resource.Resource {
	return &gatewayTier1GatewayResource{}
}

type gatewayTier1GatewayResource struct {
	client *client
}

func (r *gatewayTier1GatewayResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gateway_tier1_gateway"
}
func (r *gatewayTier1GatewayResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.Tier1GatewaySchema())
}
func (r *gatewayTier1GatewayResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *gatewayTier1GatewayResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GatewayTier1GatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayTier1Gateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	created, err := c.CreateTier1Gateway(ctx, &v2.CreateTier1GatewayRequest{
		Name:         plan.Name.ValueString(),
		Parent:       plan.Parent.ValueString(),
		Tier1Gateway: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create GatewayTier1Gateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayTier1Gateway(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayTier1GatewayResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state GatewayTier1GatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	got, err := c.GetTier1Gateway(ctx, &v2.GetTier1GatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read GatewayTier1Gateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayTier1Gateway(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *gatewayTier1GatewayResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan GatewayTier1GatewayModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandGatewayTier1Gateway(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetTier1Gateway(ctx, &v2.GetTier1GatewayRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read GatewayTier1Gateway before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateTier1Gateway(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update GatewayTier1Gateway", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenGatewayTier1Gateway(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *gatewayTier1GatewayResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state GatewayTier1GatewayModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewGatewaysClient(r.client.conn)
	_, err := c.DeleteTier1Gateway(ctx, &v2.DeleteTier1GatewayRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete GatewayTier1Gateway", err.Error())
		return
	}
}
func (r *gatewayTier1GatewayResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, gatewayTier1GatewayCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
