// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v21 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
	v2 "github.com/tetrateio/tetrate/api/tsb/types/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const istioGatewayGatewayCollection = "gateways"

var (
	_ resource.Resource                = (*istioGatewayGatewayResource)(nil)
	_ resource.ResourceWithConfigure   = (*istioGatewayGatewayResource)(nil)
	_ resource.ResourceWithImportState = (*istioGatewayGatewayResource)(nil)
)

// NewIstioGatewayGatewayResource constructs the tsb_istio_gateway_gateway resource.
func NewIstioGatewayGatewayResource() resource.Resource {
	return &istioGatewayGatewayResource{}
}

type istioGatewayGatewayResource struct {
	client *client
}

func (r *istioGatewayGatewayResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_istio_gateway_gateway"
}
func (r *istioGatewayGatewayResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.IstioObjectSchema())
}
func (r *istioGatewayGatewayResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *istioGatewayGatewayResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan IstioObjectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandIstioObject(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v21.NewIstioGatewayClient(r.client.conn)
	created, err := c.CreateGateway(ctx, &v2.CreateIstioObjectRequest{
		Name:   plan.Name.ValueString(),
		Object: msg,
		Parent: plan.Parent.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create IstioGatewayGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenIstioObject(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *istioGatewayGatewayResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state IstioObjectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v21.NewIstioGatewayClient(r.client.conn)
	got, err := c.GetGateway(ctx, &v2.GetIstioObjectRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read IstioGatewayGateway", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenIstioObject(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *istioGatewayGatewayResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan IstioObjectModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandIstioObject(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v21.NewIstioGatewayClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetGateway(ctx, &v2.GetIstioObjectRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read IstioGatewayGateway before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateGateway(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update IstioGatewayGateway", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenIstioObject(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *istioGatewayGatewayResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state IstioObjectModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v21.NewIstioGatewayClient(r.client.conn)
	_, err := c.DeleteGateway(ctx, &v2.DeleteIstioObjectRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete IstioGatewayGateway", err.Error())
		return
	}
}
func (r *istioGatewayGatewayResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, istioGatewayGatewayCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
