// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"reflect"
	"sort"
	"testing"

	schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"

	v1alpha1 "github.com/tetrateio/tetrate/api/install/dataplane/v1alpha1"
	v21 "github.com/tetrateio/tetrate/api/tsb/application/v2"
	v22 "github.com/tetrateio/tetrate/api/tsb/extension/v2"
	v23 "github.com/tetrateio/tetrate/api/tsb/gateway/v2"
	v25 "github.com/tetrateio/tetrate/api/tsb/istiointernal/v2"
	v26 "github.com/tetrateio/tetrate/api/tsb/profile/v2"
	v27 "github.com/tetrateio/tetrate/api/tsb/rbac/v2"
	v28 "github.com/tetrateio/tetrate/api/tsb/security/v2"
	v29 "github.com/tetrateio/tetrate/api/tsb/traffic/v2"
	v24 "github.com/tetrateio/tetrate/api/tsb/types/v2"
	v2 "github.com/tetrateio/tetrate/api/tsb/v2"
)

// TestModelSchemaParity asserts each generated model covers exactly its schema's attributes.
func TestModelSchemaParity(t *testing.T) {
	cases := []struct {
		name   string
		schema schema.Schema
		model  reflect.Type
	}{{
		model:  reflect.TypeOf(APIModel{}),
		name:   "api",
		schema: v2.APISchema(),
	}, {
		model:  reflect.TypeOf(ApplicationAPIModel{}),
		name:   "application_api",
		schema: v21.APISchema(),
	}, {
		model:  reflect.TypeOf(ApplicationApplicationModel{}),
		name:   "application_application",
		schema: v21.ApplicationSchema(),
	}, {
		model:  reflect.TypeOf(ClusterModel{}),
		name:   "cluster",
		schema: v2.ClusterSchema(),
	}, {
		model:  reflect.TypeOf(ClusterOnboardingConfigModel{}),
		name:   "cluster_onboarding_config",
		schema: v2.ClusterOnboardingConfigSchema(),
	}, {
		model:  reflect.TypeOf(ExtensionWasmExtensionModel{}),
		name:   "extension_wasm_extension",
		schema: v22.WasmExtensionSchema(),
	}, {
		model:  reflect.TypeOf(GatewayEgressGatewayModel{}),
		name:   "gateway_egress_gateway",
		schema: v23.EgressGatewaySchema(),
	}, {
		model:  reflect.TypeOf(GatewayGatewayModel{}),
		name:   "gateway_gateway",
		schema: v23.GatewaySchema(),
	}, {
		model:  reflect.TypeOf(GatewayGroupModel{}),
		name:   "gateway_group",
		schema: v23.GroupSchema(),
	}, {
		model:  reflect.TypeOf(GatewayIngressGatewayModel{}),
		name:   "gateway_ingress_gateway",
		schema: v23.IngressGatewaySchema(),
	}, {
		model:  reflect.TypeOf(GatewayInstallGatewayModel{}),
		name:   "gateway_install_gateway",
		schema: v1alpha1.GatewaySpecSchema(),
	}, {
		model:  reflect.TypeOf(GatewayInstallGatewayTemplateModel{}),
		name:   "gateway_install_gateway_template",
		schema: v23.InstallGatewayTemplateSchema(),
	}, {
		model:  reflect.TypeOf(GatewaySharedGatewayReferenceGrantModel{}),
		name:   "gateway_shared_gateway_reference_grant",
		schema: v23.SharedGatewayReferenceGrantSchema(),
	}, {
		model:  reflect.TypeOf(GatewayTier1GatewayModel{}),
		name:   "gateway_tier1_gateway",
		schema: v23.Tier1GatewaySchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_gateway_authorization_policy",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_gateway_gateway",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_gateway_request_authentication",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_gateway_virtual_service",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_internal_direct_envoy_filter",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_internal_direct_service_entry",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_internal_direct_wasm_plugin",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_security_authorization_policy",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_security_peer_authentication",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_security_request_authentication",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_traffic_destination_rule",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_traffic_sidecar",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstioObjectModel{}),
		name:   "istio_traffic_virtual_service",
		schema: v24.IstioObjectSchema(),
	}, {
		model:  reflect.TypeOf(IstiointernalGroupModel{}),
		name:   "istiointernal_group",
		schema: v25.GroupSchema(),
	}, {
		model:  reflect.TypeOf(OIDCModel{}),
		name:   "oidc",
		schema: v2.OIDCSchema(),
	}, {
		model:  reflect.TypeOf(OrganizationModel{}),
		name:   "organization",
		schema: v2.OrganizationSchema(),
	}, {
		model:  reflect.TypeOf(OrganizationSettingModel{}),
		name:   "organization_setting",
		schema: v2.OrganizationSettingSchema(),
	}, {
		model:  reflect.TypeOf(ProfileProfileModel{}),
		name:   "profile_profile",
		schema: v26.ProfileSchema(),
	}, {
		model:  reflect.TypeOf(RbacRoleModel{}),
		name:   "rbac_role",
		schema: v27.RoleSchema(),
	}, {
		model:  reflect.TypeOf(SecurityGroupModel{}),
		name:   "security_group",
		schema: v28.GroupSchema(),
	}, {
		model:  reflect.TypeOf(SecuritySecuritySettingModel{}),
		name:   "security_security_setting",
		schema: v28.SecuritySettingSchema(),
	}, {
		model:  reflect.TypeOf(SecurityServiceSecuritySettingModel{}),
		name:   "security_service_security_setting",
		schema: v28.ServiceSecuritySettingSchema(),
	}, {
		model:  reflect.TypeOf(ServiceAccountModel{}),
		name:   "service_account",
		schema: v2.ServiceAccountSchema(),
	}, {
		model:  reflect.TypeOf(TeamModel{}),
		name:   "team",
		schema: v2.TeamSchema(),
	}, {
		model:  reflect.TypeOf(TenantModel{}),
		name:   "tenant",
		schema: v2.TenantSchema(),
	}, {
		model:  reflect.TypeOf(TenantSettingModel{}),
		name:   "tenant_setting",
		schema: v2.TenantSettingSchema(),
	}, {
		model:  reflect.TypeOf(TrafficGroupModel{}),
		name:   "traffic_group",
		schema: v29.GroupSchema(),
	}, {
		model:  reflect.TypeOf(TrafficServiceRouteModel{}),
		name:   "traffic_service_route",
		schema: v29.ServiceRouteSchema(),
	}, {
		model:  reflect.TypeOf(TrafficServiceTrafficSettingModel{}),
		name:   "traffic_service_traffic_setting",
		schema: v29.ServiceTrafficSettingSchema(),
	}, {
		model:  reflect.TypeOf(TrafficTrafficSettingModel{}),
		name:   "traffic_traffic_setting",
		schema: v29.TrafficSettingSchema(),
	}, {
		model:  reflect.TypeOf(UserModel{}),
		name:   "user",
		schema: v2.UserSchema(),
	}, {
		model:  reflect.TypeOf(WorkspaceModel{}),
		name:   "workspace",
		schema: v2.WorkspaceSchema(),
	}, {
		model:  reflect.TypeOf(WorkspaceSettingModel{}),
		name:   "workspace_setting",
		schema: v2.WorkspaceSettingSchema(),
	}}
	for _, c := range cases {
		var want []string
		for name := range c.schema.Attributes {
			want = append(want, name)
		}
		sort.Strings(want)
		var got []string
		for i := 0; i < c.model.NumField(); i++ {
			if tag, ok := c.model.Field(i).Tag.Lookup("tfsdk"); ok {
				got = append(got, tag)
			}
		}
		sort.Strings(got)
		if !reflect.DeepEqual(want, got) {
			t.Errorf("%s: model/schema attribute mismatch\n schema: %v\n model:  %v", c.name, want, got)
		}
	}
}
