// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/security/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const securitySecuritySettingCollection = "settings"

var (
	_ resource.Resource                = (*securitySecuritySettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*securitySecuritySettingResource)(nil)
	_ resource.ResourceWithImportState = (*securitySecuritySettingResource)(nil)
)

// NewSecuritySecuritySettingResource constructs the tsb_security_security_setting resource.
func NewSecuritySecuritySettingResource() resource.Resource {
	return &securitySecuritySettingResource{}
}

type securitySecuritySettingResource struct {
	client *client
}

func (r *securitySecuritySettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_security_security_setting"
}
func (r *securitySecuritySettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.SecuritySettingSchema())
}
func (r *securitySecuritySettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *securitySecuritySettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SecuritySecuritySettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandSecuritySecuritySetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	created, err := c.CreateSettings(ctx, &v2.CreateSecuritySettingsRequest{
		Name:     plan.Name.ValueString(),
		Parent:   plan.Parent.ValueString(),
		Settings: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create SecuritySecuritySetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecuritySecuritySetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *securitySecuritySettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SecuritySecuritySettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	got, err := c.GetSettings(ctx, &v2.GetSecuritySettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read SecuritySecuritySetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecuritySecuritySetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *securitySecuritySettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SecuritySecuritySettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandSecuritySecuritySetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetSettings(ctx, &v2.GetSecuritySettingsRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read SecuritySecuritySetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateSettings(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update SecuritySecuritySetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecuritySecuritySetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *securitySecuritySettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SecuritySecuritySettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	_, err := c.DeleteSettings(ctx, &v2.DeleteSecuritySettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete SecuritySecuritySetting", err.Error())
		return
	}
}
func (r *securitySecuritySettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, securitySecuritySettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
