// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/security/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const securityServiceSecuritySettingCollection = "servicesettings"

var (
	_ resource.Resource                = (*securityServiceSecuritySettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*securityServiceSecuritySettingResource)(nil)
	_ resource.ResourceWithImportState = (*securityServiceSecuritySettingResource)(nil)
)

// NewSecurityServiceSecuritySettingResource constructs the tsb_security_service_security_setting resource.
func NewSecurityServiceSecuritySettingResource() resource.Resource {
	return &securityServiceSecuritySettingResource{}
}

type securityServiceSecuritySettingResource struct {
	client *client
}

func (r *securityServiceSecuritySettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_security_service_security_setting"
}
func (r *securityServiceSecuritySettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.ServiceSecuritySettingSchema())
}
func (r *securityServiceSecuritySettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *securityServiceSecuritySettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SecurityServiceSecuritySettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandSecurityServiceSecuritySetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	created, err := c.CreateServiceSecuritySettings(ctx, &v2.CreateServiceSecuritySettingsRequest{
		Name:     plan.Name.ValueString(),
		Parent:   plan.Parent.ValueString(),
		Settings: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create SecurityServiceSecuritySetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecurityServiceSecuritySetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *securityServiceSecuritySettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SecurityServiceSecuritySettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	got, err := c.GetServiceSecuritySettings(ctx, &v2.GetServiceSecuritySettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read SecurityServiceSecuritySetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecurityServiceSecuritySetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *securityServiceSecuritySettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SecurityServiceSecuritySettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandSecurityServiceSecuritySetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetServiceSecuritySettings(ctx, &v2.GetServiceSecuritySettingsRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read SecurityServiceSecuritySetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateServiceSecuritySettings(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update SecurityServiceSecuritySetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenSecurityServiceSecuritySetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *securityServiceSecuritySettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state SecurityServiceSecuritySettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewSecurityClient(r.client.conn)
	_, err := c.DeleteServiceSecuritySettings(ctx, &v2.DeleteServiceSecuritySettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete SecurityServiceSecuritySetting", err.Error())
		return
	}
}
func (r *securityServiceSecuritySettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, securityServiceSecuritySettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
