// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v2 "github.com/tetrateio/tetrate/api/tsb/v2"
)

const teamCollection = "teams"

var (
	_ resource.Resource                = (*teamResource)(nil)
	_ resource.ResourceWithConfigure   = (*teamResource)(nil)
	_ resource.ResourceWithImportState = (*teamResource)(nil)
)

// NewTeamResource constructs the tsb_team resource.
func NewTeamResource() resource.Resource {
	return &teamResource{}
}

type teamResource struct {
	client *client
}

func (r *teamResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_team"
}
func (r *teamResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.TeamSchema())
}
func (r *teamResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *teamResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TeamModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTeam(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTeamsClient(r.client.conn)
	created, err := c.CreateTeam(ctx, &v2.CreateTeamRequest{
		Name:   plan.Name.ValueString(),
		Parent: plan.Parent.ValueString(),
		Team:   msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create Team", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTeam(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *teamResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TeamModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTeamsClient(r.client.conn)
	got, err := c.GetTeam(ctx, &v2.GetTeamRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read Team", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTeam(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *teamResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TeamModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTeam(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTeamsClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetTeam(ctx, &v2.GetTeamRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read Team before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateTeam(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update Team", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenTeam(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *teamResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TeamModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTeamsClient(r.client.conn)
	_, err := c.DeleteTeam(ctx, &v2.DeleteTeamRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete Team", err.Error())
		return
	}
}
func (r *teamResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, teamCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
