// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const tenantSettingCollection = "settings"

var (
	_ resource.Resource                = (*tenantSettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*tenantSettingResource)(nil)
	_ resource.ResourceWithImportState = (*tenantSettingResource)(nil)
)

// NewTenantSettingResource constructs the tsb_tenant_setting resource.
func NewTenantSettingResource() resource.Resource {
	return &tenantSettingResource{}
}

type tenantSettingResource struct {
	client *client
}

func (r *tenantSettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tenant_setting"
}
func (r *tenantSettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.TenantSettingSchema())
}
func (r *tenantSettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *tenantSettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TenantSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTenantSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTenantsClient(r.client.conn)
	created, err := c.CreateSetting(ctx, &v2.CreateTenantSettingRequest{
		Name:    plan.Name.ValueString(),
		Parent:  plan.Parent.ValueString(),
		Setting: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create TenantSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTenantSetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *tenantSettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TenantSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTenantsClient(r.client.conn)
	got, err := c.GetSetting(ctx, &v2.GetTenantSettingRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read TenantSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTenantSetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *tenantSettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TenantSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTenantSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTenantsClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetSetting(ctx, &v2.GetTenantSettingRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read TenantSetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateSetting(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update TenantSetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenTenantSetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *tenantSettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TenantSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTenantsClient(r.client.conn)
	_, err := c.DeleteSetting(ctx, &v2.DeleteTenantSettingRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete TenantSetting", err.Error())
		return
	}
}
func (r *tenantSettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, tenantSettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
