// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/traffic/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const trafficServiceRouteCollection = "serviceroutes"

var (
	_ resource.Resource                = (*trafficServiceRouteResource)(nil)
	_ resource.ResourceWithConfigure   = (*trafficServiceRouteResource)(nil)
	_ resource.ResourceWithImportState = (*trafficServiceRouteResource)(nil)
)

// NewTrafficServiceRouteResource constructs the tsb_traffic_service_route resource.
func NewTrafficServiceRouteResource() resource.Resource {
	return &trafficServiceRouteResource{}
}

type trafficServiceRouteResource struct {
	client *client
}

func (r *trafficServiceRouteResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_traffic_service_route"
}
func (r *trafficServiceRouteResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.ServiceRouteSchema())
}
func (r *trafficServiceRouteResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *trafficServiceRouteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TrafficServiceRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficServiceRoute(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	created, err := c.CreateServiceRoute(ctx, &v2.CreateServiceRouteRequest{
		Name:         plan.Name.ValueString(),
		Parent:       plan.Parent.ValueString(),
		ServiceRoute: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create TrafficServiceRoute", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceRoute(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficServiceRouteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TrafficServiceRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	got, err := c.GetServiceRoute(ctx, &v2.GetServiceRouteRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read TrafficServiceRoute", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceRoute(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *trafficServiceRouteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TrafficServiceRouteModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficServiceRoute(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetServiceRoute(ctx, &v2.GetServiceRouteRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read TrafficServiceRoute before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateServiceRoute(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update TrafficServiceRoute", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceRoute(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficServiceRouteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TrafficServiceRouteModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	_, err := c.DeleteServiceRoute(ctx, &v2.DeleteServiceRouteRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete TrafficServiceRoute", err.Error())
		return
	}
}
func (r *trafficServiceRouteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, trafficServiceRouteCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
