// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	v2 "github.com/tetrateio/tetrate/api/tsb/traffic/v2"
)

const trafficTrafficSettingCollection = "settings"

var (
	_ resource.Resource                = (*trafficTrafficSettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*trafficTrafficSettingResource)(nil)
	_ resource.ResourceWithImportState = (*trafficTrafficSettingResource)(nil)
)

// NewTrafficTrafficSettingResource constructs the tsb_traffic_traffic_setting resource.
func NewTrafficTrafficSettingResource() resource.Resource {
	return &trafficTrafficSettingResource{}
}

type trafficTrafficSettingResource struct {
	client *client
}

func (r *trafficTrafficSettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_traffic_traffic_setting"
}
func (r *trafficTrafficSettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.TrafficSettingSchema())
}
func (r *trafficTrafficSettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *trafficTrafficSettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TrafficTrafficSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficTrafficSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	created, err := c.CreateSettings(ctx, &v2.CreateTrafficSettingsRequest{
		Name:     plan.Name.ValueString(),
		Parent:   plan.Parent.ValueString(),
		Settings: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create TrafficTrafficSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficTrafficSetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficTrafficSettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TrafficTrafficSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	got, err := c.GetSettings(ctx, &v2.GetTrafficSettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read TrafficTrafficSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficTrafficSetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *trafficTrafficSettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TrafficTrafficSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficTrafficSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetSettings(ctx, &v2.GetTrafficSettingsRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read TrafficTrafficSetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateSettings(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update TrafficTrafficSetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficTrafficSetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficTrafficSettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TrafficTrafficSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	_, err := c.DeleteSettings(ctx, &v2.DeleteTrafficSettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete TrafficTrafficSetting", err.Error())
		return
	}
}
func (r *trafficTrafficSettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, trafficTrafficSettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
