// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/traffic/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const trafficServiceTrafficSettingCollection = "servicesettings"

var (
	_ resource.Resource                = (*trafficServiceTrafficSettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*trafficServiceTrafficSettingResource)(nil)
	_ resource.ResourceWithImportState = (*trafficServiceTrafficSettingResource)(nil)
)

// NewTrafficServiceTrafficSettingResource constructs the tsb_traffic_service_traffic_setting resource.
func NewTrafficServiceTrafficSettingResource() resource.Resource {
	return &trafficServiceTrafficSettingResource{}
}

type trafficServiceTrafficSettingResource struct {
	client *client
}

func (r *trafficServiceTrafficSettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_traffic_service_traffic_setting"
}
func (r *trafficServiceTrafficSettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.ServiceTrafficSettingSchema())
}
func (r *trafficServiceTrafficSettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *trafficServiceTrafficSettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TrafficServiceTrafficSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficServiceTrafficSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	created, err := c.CreateServiceTrafficSetting(ctx, &v2.CreateServiceTrafficSettingRequest{
		Name:           plan.Name.ValueString(),
		Parent:         plan.Parent.ValueString(),
		ServiceSetting: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create TrafficServiceTrafficSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceTrafficSetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficServiceTrafficSettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TrafficServiceTrafficSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	got, err := c.GetServiceTrafficSetting(ctx, &v2.GetServiceTrafficSettingRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read TrafficServiceTrafficSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceTrafficSetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *trafficServiceTrafficSettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TrafficServiceTrafficSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandTrafficServiceTrafficSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetServiceTrafficSetting(ctx, &v2.GetServiceTrafficSettingRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read TrafficServiceTrafficSetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateServiceTrafficSetting(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update TrafficServiceTrafficSetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenTrafficServiceTrafficSetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *trafficServiceTrafficSettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TrafficServiceTrafficSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewTrafficClient(r.client.conn)
	_, err := c.DeleteServiceTrafficSetting(ctx, &v2.DeleteServiceTrafficSettingRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete TrafficServiceTrafficSetting", err.Error())
		return
	}
}
func (r *trafficServiceTrafficSettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, trafficServiceTrafficSettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
