// Copyright (c) Tetrate, Inc 2026 All Rights Reserved.
// Code generated by gen-provider. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	path "github.com/hashicorp/terraform-plugin-framework/path"
	resource "github.com/hashicorp/terraform-plugin-framework/resource"
	v2 "github.com/tetrateio/tetrate/api/tsb/v2"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const workspaceSettingCollection = "settings"

var (
	_ resource.Resource                = (*workspaceSettingResource)(nil)
	_ resource.ResourceWithConfigure   = (*workspaceSettingResource)(nil)
	_ resource.ResourceWithImportState = (*workspaceSettingResource)(nil)
)

// NewWorkspaceSettingResource constructs the tsb_workspace_setting resource.
func NewWorkspaceSettingResource() resource.Resource {
	return &workspaceSettingResource{}
}

type workspaceSettingResource struct {
	client *client
}

func (r *workspaceSettingResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_workspace_setting"
}
func (r *workspaceSettingResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = fixupSchema(v2.WorkspaceSettingSchema())
}
func (r *workspaceSettingResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("Expected *client, got %T. This is a provider bug.", req.ProviderData))
		return
	}
	r.client = c
}
func (r *workspaceSettingResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan WorkspaceSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandWorkspaceSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWorkspacesClient(r.client.conn)
	created, err := c.CreateSettings(ctx, &v2.CreateWorkspaceSettingsRequest{
		Name:     plan.Name.ValueString(),
		Parent:   plan.Parent.ValueString(),
		Settings: msg,
	})
	if err != nil {
		resp.Diagnostics.AddError("Unable to create WorkspaceSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenWorkspaceSetting(ctx, created, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *workspaceSettingResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state WorkspaceSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWorkspacesClient(r.client.conn)
	got, err := c.GetSettings(ctx, &v2.GetWorkspaceSettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Unable to read WorkspaceSetting", err.Error())
		return
	}
	resp.Diagnostics.Append(flattenWorkspaceSetting(ctx, got, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
func (r *workspaceSettingResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan WorkspaceSettingModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	msg, d := expandWorkspaceSetting(ctx, &plan)
	resp.Diagnostics.Append(d...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWorkspacesClient(r.client.conn)
	// Update takes the full resource including the server-managed etag, which the
	// Terraform model intentionally drops; fetch the current one first.
	current, err := c.GetSettings(ctx, &v2.GetWorkspaceSettingsRequest{Fqn: plan.ID.ValueString()})
	if err != nil {
		resp.Diagnostics.AddError("Unable to read WorkspaceSetting before update", err.Error())
		return
	}
	msg.Fqn = current.Fqn
	msg.Etag = current.Etag
	updated, err2 := c.UpdateSettings(ctx, msg)
	if err2 != nil {
		resp.Diagnostics.AddError("Unable to update WorkspaceSetting", err2.Error())
		return
	}
	resp.Diagnostics.Append(flattenWorkspaceSetting(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}
func (r *workspaceSettingResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state WorkspaceSettingModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	c := v2.NewWorkspacesClient(r.client.conn)
	_, err := c.DeleteSettings(ctx, &v2.DeleteWorkspaceSettingsRequest{Fqn: state.ID.ValueString()})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return
		}
		resp.Diagnostics.AddError("Unable to delete WorkspaceSetting", err.Error())
		return
	}
}
func (r *workspaceSettingResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	fqn := req.ID
	parent, name := fqnParentName(fqn, workspaceSettingCollection)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), fqn)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("parent"), parent)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
}
