# This workflow builds and checks the Terraform provider on every PR.

name: Go

on:
  pull_request:
    branches: [ "*" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Configure SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TETRATE_CI_SSH_PRIVATE_KEY }}
    - name: Disable Strict Host Key Checking for SSH
      run: mkdir -p ~/.ssh && echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Pull over SSH instead of HTTPS
      run: echo -e '[url "git@github.com:"]\n\tinsteadOf = https://github.com/' | sudo tee /etc/gitconfig
    - name: Install tfplugindocs prerequisite (terraform CLI)
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Verify generated code, docs, and formatting are up to date
      run: make check
      env:
        GOPRIVATE: github.com/tetrateio/*

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Configure SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.TETRATE_CI_SSH_PRIVATE_KEY }}
    - name: Disable Strict Host Key Checking for SSH
      run: mkdir -p ~/.ssh && echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Pull over SSH instead of HTTPS
      run: echo -e '[url "git@github.com:"]\n\tinsteadOf = https://github.com/' | sudo tee /etc/gitconfig
    - name: Build
      run: make build
      env:
        GOPRIVATE: github.com/tetrateio/*
    - name: Test
      run: make test
      env:
        GOPRIVATE: github.com/tetrateio/*

