# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Install licenser
      run: 'go install github.com/liamawhite/licenser@v0.7.0'
    - name: Configure SSH Agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TETRATE_CI_SSH_PRIVATE_KEY }}
    - name: Disable Strict Host Key Checking for SSH
      run: mkdir -p ~/.ssh && echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Pull over SSH instead of HTTPS
      working-directory: .
      run: echo -e '[url "git@github.com:"]\n\tinsteadOf = https://github.com/' | sudo tee /etc/gitconfig

    - name: Verify licenses
      run: make check
      env:
        GOPRIVATE: github.com/tetrateio/*

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Configure SSH Agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.TETRATE_CI_SSH_PRIVATE_KEY }}
    - name: Disable Strict Host Key Checking for SSH
      run: mkdir -p ~/.ssh && echo -e "\tStrictHostKeyChecking no" >> ~/.ssh/config && ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Pull over SSH instead of HTTPS
      working-directory: .
      run: echo -e '[url "git@github.com:"]\n\tinsteadOf = https://github.com/' | sudo tee /etc/gitconfig

    - name: Build
      run: make build
      env:
        GOPRIVATE: github.com/tetrateio/*
    

